services:
  hawkstars:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - GENERATE_SOURCEMAP=false
      # Add your environment variables here
      # - DATABASE_URL=your_database_url
      # - NEXTAUTH_SECRET=your_secret
      # - NEXTAUTH_URL=http://localhost:8000
    # volumes:
    #   - ./uploads:/app/uploads  # If you need persistent storage
    restart: unless-stopped
    depends_on:
      - database

  database:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - 'mongo_data:/data/db'
    restart: unless-stopped
volumes:
  mongo_data:
