services:
  hawkstars:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - '3000:3000'
    restart: unless-stopped
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=hawkstars
    volumes:
      - 'mongo_data:/data/db'
    # healthcheck:
    #   test: ['CMD-SHELL', "mongosh --eval 'db.runCommand({ ping: 1 })'"]
    #   interval: 10s
    #   retries: 5
    #   start_period: 30s
    #   timeout: 10s
volumes:
  mongo_data:
