server {
    server_name hawkstars.org;

    client_max_body_size 50M;   # pick a limit that fits your media
    
    # Let's Encrypt challenge
    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    # Static assets - no rate limiting
    location ~* \.(jpg|jpeg|png|gif|ico|css|svg|webp)$ {
        proxy_pass http://localhost:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    
       # Optional: add caching
       expires 7d;
       add_header Cache-Control "public, immutable";
    }

    # CSS, JS, fonts - no limits
    location ~* \.(css|js|woff|woff2|ttf|eot|otf)$ {
        proxy_pass http://localhost:3000;
        proxy_set_header Host $host;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    location / {
        limit_req zone=mylimit burst=30 delay=10;
        proxy_pass http://localhost:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/hawkstars.org/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/hawkstars.org/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}

server {
    if ($host = hawkstars.org) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name hawkstars.org;
    return 404; # managed by Certbot
}

server {
   listen 443 ssl;
   server_name www.hawkstars.org;
    ssl_certificate /etc/letsencrypt/live/hawkstars.org/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/hawkstars.org/privkey.pem; # managed by Certbot

    return 301 https://hawkstars.org$request_uri;

}


server {
    if ($host = www.hawkstars.org) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


   listen 80;
   server_name www.hawkstars.org;
    return 404; # managed by Certbot
}