/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    artworks: Artwork;
    'board-members': BoardMember;
    contributions: Contribution;
    curators: Curator;
    hawk_projects: HawkProject;
    partners: Partner;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    artworks: ArtworksSelect<false> | ArtworksSelect<true>;
    'board-members': BoardMembersSelect<false> | BoardMembersSelect<true>;
    contributions: ContributionsSelect<false> | ContributionsSelect<true>;
    curators: CuratorsSelect<false> | CuratorsSelect<true>;
    hawk_projects: HawkProjectsSelect<false> | HawkProjectsSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'pt') | ('en' | 'pt')[];
  globals: {
    header: Header;
    footer: Footer;
    'main-page': MainPage;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'main-page': MainPageSelect<false> | MainPageSelect<true>;
  };
  locale: 'en' | 'pt';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  isAdmin?: boolean | null;
  isEditor?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Upload and manage media assets such as images used throughout the website. Use a image compression tool to optimize images before uploading to improve performance. Ideally in webP
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Alternative text for the media item, used for accessibility.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artworks".
 */
export interface Artwork {
  id: string;
  title: string;
  slug?: string | null;
  artist: string | Curator;
  synopsis: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  image: string | Media;
  is_sold?: boolean | null;
  year?: number | null;
  price: string;
  settings?: string | null;
  tiragem?: string | null;
  dimensions?: string | null;
  extra?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "curators".
 */
export interface Curator {
  id: string;
  name: string;
  slug: string;
  location?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image: string | Media;
  seo?: SEO;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SEO".
 */
export interface SEO {
  seo?: SeoFields;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SeoFields".
 */
export interface SeoFields {
  title?: string | null;
  /**
   * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
   */
  image?: (string | null) | Media;
  description?: string | null;
}
/**
 * Board Members of the Association
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "board-members".
 */
export interface BoardMember {
  id: string;
  name: string;
  /**
   * Section out of the three that is to add the member
   */
  section: 'geral' | 'fiscal' | 'board';
  title:
    | 'president'
    | 'vice_president'
    | 'vogal'
    | 'f_secretary'
    | 'm_secretary'
    | 'substitute'
    | 'treasurer'
    | 'rapporteur_secretary';
  department?: string | null;
  photo?: (string | null) | Media;
  /**
   * Social Media Links for this entry
   */
  links?:
    | {
        platform:
          | 'linkedin'
          | 'twitter'
          | 'facebook'
          | 'instagram'
          | 'website'
          | 'email'
          | 'youtube'
          | 'github'
          | 'tiktok'
          | 'whatsapp';
        url: string;
        /**
         * Toggle visibility of this link
         */
        isVisible?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Position to be ordered to be shown on the page
   */
  position: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage organization contributions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contributions".
 */
export interface Contribution {
  id: string;
  donor?: string | null;
  is_confirmed?: boolean | null;
  is_anonymous?: boolean | null;
  value: number;
  contribution_date: string;
  contribution_type:
    | 'BANK'
    | 'CRYPTO'
    | 'WALL_NAME_SINGULAR'
    | 'WALL_NAME_COMPANY'
    | 'OFFICE_CHAIR'
    | 'SIMULATOR_CHAIR'
    | 'LOUNGE_CHAIR'
    | 'AUDITORIUM_CHAIR'
    | 'BUILDING_NAMING'
    | 'TRAINING_ROOM_NAMING';
  extra_info?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Collection for managing Hawk Projects
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hawk_projects".
 */
export interface HawkProject {
  id: string;
  heading: string;
  subheading?: string | null;
  description?: string | null;
  slug: string;
  type_event?: ('erasmus' | 'local_event' | 'international_event' | 'other') | null;
  page_content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Image representing the event on the events main page not on the event page itself
   */
  image: string | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: string;
  name: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  logo?: (string | null) | Media;
  country: string;
  type: 'national' | 'international';
  /**
   * Social Media Links for this entry
   */
  links?:
    | {
        platform:
          | 'linkedin'
          | 'twitter'
          | 'facebook'
          | 'instagram'
          | 'website'
          | 'email'
          | 'youtube'
          | 'github'
          | 'tiktok'
          | 'whatsapp';
        url: string;
        /**
         * Toggle visibility of this link
         */
        isVisible?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  /**
   * The title of the page displayed in the admin panel
   */
  title: string;
  /**
   * Add, remove, and reorder blocks to build the content of the page
   */
  layout?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * The URL slug for the page, e.g. "about" for www.hawkstars.com/about
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'artworks';
        value: string | Artwork;
      } | null)
    | ({
        relationTo: 'board-members';
        value: string | BoardMember;
      } | null)
    | ({
        relationTo: 'contributions';
        value: string | Contribution;
      } | null)
    | ({
        relationTo: 'curators';
        value: string | Curator;
      } | null)
    | ({
        relationTo: 'hawk_projects';
        value: string | HawkProject;
      } | null)
    | ({
        relationTo: 'partners';
        value: string | Partner;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  isAdmin?: T;
  isEditor?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artworks_select".
 */
export interface ArtworksSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  artist?: T;
  synopsis?: T;
  image?: T;
  is_sold?: T;
  year?: T;
  price?: T;
  settings?: T;
  tiragem?: T;
  dimensions?: T;
  extra?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "board-members_select".
 */
export interface BoardMembersSelect<T extends boolean = true> {
  name?: T;
  section?: T;
  title?: T;
  department?: T;
  photo?: T;
  links?:
    | T
    | {
        platform?: T;
        url?: T;
        isVisible?: T;
        id?: T;
      };
  position?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contributions_select".
 */
export interface ContributionsSelect<T extends boolean = true> {
  donor?: T;
  is_confirmed?: T;
  is_anonymous?: T;
  value?: T;
  contribution_date?: T;
  contribution_type?: T;
  extra_info?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "curators_select".
 */
export interface CuratorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  location?: T;
  description?: T;
  image?: T;
  seo?: T | SEOSelect<T>;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SEO_select".
 */
export interface SEOSelect<T extends boolean = true> {
  seo?: T | SeoFieldsSelect<T>;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SeoFields_select".
 */
export interface SeoFieldsSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  description?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hawk_projects_select".
 */
export interface HawkProjectsSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  description?: T;
  slug?: T;
  type_event?: T;
  page_content?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  logo?: T;
  country?: T;
  type?: T;
  links?:
    | T
    | {
        platform?: T;
        url?: T;
        isVisible?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  layout?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This is the information about the header. Each column represents a group of navigation links
 *       that will be displayed in the header section of the website side by side or at the mobile. If it has more just 1 link it will not have a dropdown
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  /**
   * Configure the navigation columns for the header. topbar menus
   */
  columns: {
    data: {
      /**
       * Unique key for the navigation group to be used on the dropdown menu
       */
      key: string;
      /**
       * The title of the navigation group to be used on the dropdown menu. Use it when you want to have the dropdown
       */
      title?: string | null;
      links?:
        | {
            link: {
              type: 'reference' | 'custom';
              newTab?: boolean | null;
              reference?:
                | ({
                    relationTo: 'pages';
                    value: string | Page;
                  } | null)
                | ({
                    relationTo: 'hawk_projects';
                    value: string | HawkProject;
                  } | null);
              url?: string | null;
              label: string;
              /**
               * Choose how the link should be rendered.
               */
              appearance?: ('default' | 'outline') | null;
            };
            id?: string | null;
          }[]
        | null;
    };
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This is the information about the footer. Each column represents a group of navigation links
 *       that will be displayed in the footer section of the website side by side or at the mobile.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  columns?:
    | {
        /**
         * Footer column. If there is only 1 link, it will be displayed without a title.
         */
        column: {
          title?: string | null;
          data: {
            link: {
              type: 'reference' | 'custom';
              newTab?: boolean | null;
              reference?:
                | ({
                    relationTo: 'pages';
                    value: string | Page;
                  } | null)
                | ({
                    relationTo: 'hawk_projects';
                    value: string | HawkProject;
                  } | null);
              url?: string | null;
              label: string;
              /**
               * Choose how the link should be rendered.
               */
              appearance?: ('default' | 'outline') | null;
            };
            id?: string | null;
          }[];
        };
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configure the main landing page of the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "main-page".
 */
export interface MainPage {
  id: string;
  layout: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        data?:
          | T
          | {
              key?: T;
              title?: T;
              links?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                          appearance?: T;
                        };
                    id?: T;
                  };
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        column?:
          | T
          | {
              title?: T;
              data?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                          appearance?: T;
                        };
                    id?: T;
                  };
            };
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "main-page_select".
 */
export interface MainPageSelect<T extends boolean = true> {
  layout?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'pages';
      value: string | Page;
    } | null;
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  title: string;
  subtitle?: string | null;
  links?:
    | {
        link: {
          type: 'reference' | 'custom';
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'hawk_projects';
                value: string | HawkProject;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ColumnBasedBlock".
 */
export interface ColumnBasedBlock {
  columns: {
    /**
     * Lucide icon name (e.g., "User", "Mail", "Calendar")
     */
    icon?: string | null;
    title: string;
    subtitle?: string | null;
    list?:
      | {
          item: string;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'columnBased';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GallerySliderBlock".
 */
export interface GallerySliderBlock {
  images: {
    image: string | Media;
    id?: string | null;
  }[];
  /**
   * Enable automatic slide transition
   */
  autoplay?: boolean | null;
  /**
   * Delay between slides in milliseconds (1000-10000)
   */
  autoplayDelay?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallerySlider';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  /**
   * Badge label above heading (e.g., "PLATFORM")
   */
  badge?: string | null;
  /**
   * Main heading text
   */
  heading: string;
  /**
   * Call-to-action button text
   */
  ctaText?: string | null;
  /**
   * URL for the CTA button
   */
  ctaLink?: string | null;
  /**
   * Image displayed above the heading
   */
  headerImage?: (string | null) | Media;
  /**
   * Feature cards displayed in grid (up to 4)
   */
  features?:
    | {
        /**
         * Icon type for this feature
         */
        icon: 'globe' | 'rocket' | 'expand' | 'wrench';
        /**
         * Feature title
         */
        title: string;
        /**
         * Feature description
         */
        description: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentWithImageBlock".
 */
export interface ContentWithImageBlock {
  title: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  image: string | Media;
  /**
   * Position of the image relative to the content
   */
  imagePosition?: ('left' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contentWithImage';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlock".
 */
export interface VideoBlock {
  /**
   * YouTube, Vimeo, or direct video URL (mp4, webm, ogg)
   */
  videoUrl: string;
  /**
   * Optional title for the video
   */
  title?: string | null;
  /**
   * Optional caption or description
   */
  caption?: string | null;
  /**
   * Auto-play video when visible
   */
  autoplay?: boolean | null;
  /**
   * Loop video playback
   */
  loop?: boolean | null;
  /**
   * Mute video by default (required for autoplay)
   */
  muted?: boolean | null;
  /**
   * Show video controls
   */
  controls?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'videoBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AccordionBlock".
 */
export interface AccordionBlock {
  items: {
    title: string;
    content: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    /**
     * Whether this accordion item should be open by default
     */
    defaultOpen?: boolean | null;
    id?: string | null;
  }[];
  /**
   * Allow multiple accordion items to be open at the same time
   */
  allowMultipleOpen?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'accordionBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Projects18Block".
 */
export interface Projects18Block {
  title: string;
  subtitle?: string | null;
  description?: string | null;
  /**
   * Select the projects you want to display in this block
   */
  projects: (string | HawkProject)[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'projects18';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProcessOneBlock".
 */
export interface ProcessOneBlock {
  title: string;
  description?: string | null;
  ctaText?: string | null;
  steps: {
    step: string;
    title: string;
    description: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'processOneBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImpactBlock".
 */
export interface ImpactBlock {
  /**
   * Main title for the impact section
   */
  title: string;
  /**
   * Optional subtitle or description
   */
  subtitle?: string | null;
  metrics: {
    /**
     * Description of what this number represents
     */
    label: string;
    /**
     * The numerical value
     */
    value: number;
    /**
     * Optional suffix (e.g., "+", "%", "€", "people")
     */
    suffix?: string | null;
    /**
     * Optional prefix (e.g., "€", "$", ">")
     */
    prefix?: string | null;
    /**
     * Lucide icon name (e.g., "Users", "Heart", "Target")
     */
    icon?: string | null;
    color?: ('blue' | 'green' | 'red' | 'yellow' | 'purple' | 'gray') | null;
    /**
     * Animate the number when it comes into view
     */
    animateOnScroll?: boolean | null;
    id?: string | null;
  }[];
  /**
   * How to display the metrics
   */
  layout?: ('grid-2' | 'grid-3' | 'grid-4' | 'row') | null;
  /**
   * Background style for the impact section
   */
  background?: ('none' | 'light-gray' | 'dark' | 'gradient') | null;
  /**
   * Text alignment for the impact section
   */
  textAlign?: ('left' | 'center' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'impactBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardGridBlock".
 */
export interface CardGridBlock {
  /**
   * Optional title for the feature section
   */
  title?: string | null;
  features: {
    heading: string;
    description: string;
    /**
     * Lucide icon name (e.g., "GitPullRequest", "SquareKanban", "RadioTower", "WandSparkles", "Layers", "BatteryCharging")
     */
    icon: string;
    id?: string | null;
  }[];
  /**
   * Optional button text (button hidden if empty)
   */
  buttonText?: string | null;
  /**
   * Optional button URL (button hidden if empty)
   */
  buttonUrl?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cardGridBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialBlock".
 */
export interface TestimonialBlock {
  /**
   * Optional title for the testimonial section
   */
  title?: string | null;
  /**
   * Optional subtitle or description
   */
  subtitle?: string | null;
  testimonials: {
    /**
     * The testimonial quote or review
     */
    quote: string;
    author: {
      /**
       * Author full name
       */
      name: string;
      /**
       * Job title or role
       */
      title?: string | null;
      /**
       * Company or organization
       */
      company?: string | null;
      /**
       * Author profile photo
       */
      avatar?: (string | null) | Media;
    };
    /**
     * Star rating (1-5 stars)
     */
    rating?: number | null;
    /**
     * Mark as featured testimonial (larger display)
     */
    featured?: boolean | null;
    id?: string | null;
  }[];
  /**
   * How to display the testimonials
   */
  layout?: ('single' | 'two-cols' | 'three-cols' | 'carousel' | 'masonry') | null;
  /**
   * Visual style of testimonials
   */
  style?: ('card' | 'quote' | 'minimal' | 'bubble') | null;
  /**
   * Display star ratings
   */
  showRatings?: boolean | null;
  backgroundColor?: ('none' | 'light-gray' | 'dark' | 'brand') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonialBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock".
 */
export interface StatsBlock {
  /**
   * Main heading (e.g., "We don't just talk we Deliver Results")
   */
  heading: string;
  /**
   * Description text under the heading
   */
  description?: string | null;
  /**
   * CTA button text (e.g., "Get Started With Us")
   */
  ctaButtonText?: string | null;
  primaryStat: {
    /**
     * Monthly value for the main statistic
     */
    monthlyValue: number;
    /**
     * Yearly value for the main statistic
     */
    yearlyValue: number;
    /**
     * Optional prefix (e.g., "$")
     */
    prefix?: string | null;
    /**
     * Optional suffix (e.g., "M")
     */
    suffix?: string | null;
  };
  /**
   * Text below primary stat (e.g., "And its just in a year")
   */
  secondaryText?: string | null;
  /**
   * Toggle button text (e.g., "Show Monthly Stats")
   */
  toggleButtonText?: string | null;
  /**
   * Add up to 4 secondary statistics displayed in a 2x2 grid
   */
  stats: {
    /**
     * Monthly value
     */
    monthlyValue: number;
    /**
     * Yearly value
     */
    yearlyValue: number;
    /**
     * Suffix (e.g., "k+", "%", "M", "+")
     */
    suffix?: string | null;
    /**
     * Optional prefix (e.g., "~")
     */
    prefix?: string | null;
    /**
     * Label for this statistic (e.g., "Team Members", "Company Growth")
     */
    label: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'statsBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextBlock".
 */
export interface TextBlock {
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Text alignment for the content
   */
  textAlign?: ('left' | 'center' | 'right' | 'justify') | null;
  /**
   * Maximum width constraint for the text content
   */
  maxWidth?: ('full' | 'large' | 'medium' | 'small') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'textBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SimpleCTABlock".
 */
export interface SimpleCTABlock {
  heading: string;
  description: string;
  buttons?: {
    primary?: {
      text?: string | null;
      url?: string | null;
    };
    secondary?: {
      text?: string | null;
      url?: string | null;
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'simpleCta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "UpdatesBlock".
 */
export interface UpdatesBlock {
  /**
   * Section heading (e.g. Resources & Whitepapers)
   */
  heading: string;
  /**
   * Section description (e.g. Explore our thoughts...)
   */
  description?: string | null;
  /**
   * Categories for filtering updates
   */
  categories: {
    /**
     * Category name (e.g. Data, AI, Security, News)
     */
    name: string;
    id?: string | null;
  }[];
  /**
   * Latest updates for the tabbed section
   */
  latestUpdates: {
    title: string;
    category: string;
    date: string;
    authors?:
      | {
          avatar: string;
          id?: string | null;
        }[]
      | null;
    link: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'updatesBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogosBlock".
 */
export interface LogosBlock {
  /**
   * Text for the badge (e.g. Referral Partners)
   */
  badgeText?: string | null;
  /**
   * Main heading
   */
  heading: string;
  /**
   * Description text
   */
  description?: string | null;
  /**
   * Button text (e.g. Become a partner)
   */
  buttonText?: string | null;
  /**
   * Partner logos
   */
  logos: {
    name: string;
    /**
     * Logo image URL
     */
    logo: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'logosBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}