/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type Youtube = {
  _type: 'youtube';
  url?: string;
};

export type Accordion = {
  _type: 'accordion';
  title?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  values?: Array<
    {
      _key: string;
    } & InternationalizedArrayFormattedTextValue
  >;
};

export type Social_link = {
  _type: 'social_link';
  url: string;
  type: 'facebook' | 'linkedin' | 'instagram' | 'website';
};

export type Global_village = {
  _id: string;
  _type: 'global_village';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero_block: Hero;
  second_block: Array<
    {
      _key: string;
    } & InternationalizedArrayFormattedTextValue
  >;
  third_block: Hero;
  objectives?: List;
};

export type List = {
  _type: 'list';
  title?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  list_values?: Array<
    {
      _key: string;
    } & Accordion
  >;
};

export type Hero = {
  _type: 'hero';
  title?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  paragraph: Array<
    {
      _key: string;
    } & InternationalizedArrayFormattedTextValue
  >;
};

export type Board_member = {
  _id: string;
  _type: 'board_member';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  section: 'geral' | 'fiscal' | 'board';
  title:
    | 'president'
    | 'vice_president'
    | 'vogal'
    | 'f_secretary'
    | 'm_secretary'
    | 'substitute'
    | 'treasurer'
    | 'rapporteur_secretary';
  image?: Array<
    {
      _key: string;
    } & CloudinaryAsset
  >;
  links?: Array<
    {
      _key: string;
    } & Social_link
  >;
  position?: number;
};

export type Contribution = {
  _id: string;
  _type: 'contribution';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  donor: string;
  is_confirmed?: boolean;
  is_anonymous?: boolean;
  value: number;
  contribution_date: string;
  contribution_type:
    | 'BANK'
    | 'CRYPTO'
    | 'WALL_NAME_SINGULAR'
    | 'WALL_NAME_COMPANY'
    | 'OFFICE_CHAIR'
    | 'SIMULATOR_CHAIR'
    | 'LOUNGE_CHAIR'
    | 'AUDITORIUM_CHAIR'
    | 'BUILDING_NAMING'
    | 'TRAINING_ROOM_NAMING';
  extra_info?: string;
};

export type Event = {
  _id: string;
  _type: 'event';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  type_event?: 'erasmus' | 'local_event' | 'international_event' | 'other';
  description?: Array<
    {
      _key: string;
    } & InternationalizedArrayFormattedTextValue
  >;
  image?: Array<
    {
      _key: string;
    } & CloudinaryAsset
  >;
};

export type Art = {
  _id: string;
  _type: 'art';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  slug?: Slug;
  synopsis?: Array<
    {
      _key: string;
    } & InternationalizedArrayFormattedTextValue
  >;
  image?: CloudinaryAsset;
  is_sold?: boolean;
  artist?: string;
  year?: number;
  price?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  settings?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  tiragem?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  dimensions?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  extra?: Array<
    {
      _key: string;
    } & InternationalizedArrayFormattedTextValue
  >;
};

export type Curator = {
  _id: string;
  _type: 'curator';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  location?: string;
  description?: Array<
    {
      _key: string;
    } & InternationalizedArrayFormattedTextValue
  >;
  image?: CloudinaryAsset;
  google_description?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
};

export type Slug = {
  _type: 'slug';
  current: string;
  source?: string;
};

export type InternationalizedArrayFormattedTextValue = {
  _type: 'internationalizedArrayFormattedTextValue';
  value?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | ({
        _key: string;
      } & Youtube)
  >;
};

export type InternationalizedArrayStringValue = {
  _type: 'internationalizedArrayStringValue';
  value?: string;
};

export type InternationalizedArrayFormattedText = Array<
  {
    _key: string;
  } & InternationalizedArrayFormattedTextValue
>;

export type InternationalizedArrayString = Array<
  {
    _key: string;
  } & InternationalizedArrayStringValue
>;

export type CloudinaryAssetContextCustom = {
  _type: 'cloudinary.assetContextCustom';
  alt?: string;
  caption?: string;
};

export type CloudinaryAssetDerived = {
  _type: 'cloudinary.assetDerived';
  raw_transformation?: string;
  url?: string;
  secure_url?: string;
};

export type CloudinaryAsset = {
  _type: 'cloudinary.asset';
  public_id?: string;
  resource_type?: string;
  type?: string;
  format?: string;
  version?: number;
  url?: string;
  secure_url?: string;
  width?: number;
  height?: number;
  bytes?: number;
  duration?: number;
  tags?: Array<string>;
  created_at?: string;
  derived?: Array<
    {
      _key: string;
    } & CloudinaryAssetDerived
  >;
  access_mode?: string;
  context?: CloudinaryAssetContext;
};

export type CloudinaryAssetContext = {
  _type: 'cloudinary.assetContext';
  custom?: CloudinaryAssetContextCustom;
};

export type AllSanitySchemaTypes =
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | SanityAssetSourceData
  | Youtube
  | Accordion
  | Social_link
  | Global_village
  | List
  | Hero
  | Board_member
  | Contribution
  | Event
  | Art
  | Curator
  | Slug
  | InternationalizedArrayFormattedTextValue
  | InternationalizedArrayStringValue
  | InternationalizedArrayFormattedText
  | InternationalizedArrayString
  | CloudinaryAssetContextCustom
  | CloudinaryAssetDerived
  | CloudinaryAsset
  | CloudinaryAssetContext;
export declare const internalGroqTypeReferenceTo: unique symbol;
