/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type Art_property = {
  _type: 'art_property';
  title?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  value?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
};

export type Report = {
  _id: string;
  _type: 'report';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  erasmus: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'erasmus_project';
  };
  description?: Array<
    {
      _key: string;
    } & InternationalizedArrayFormattedTextValue
  >;
};

export type News = {
  _id: string;
  _type: 'news';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug?: Slug;
  description?: Array<
    {
      _key: string;
    } & InternationalizedArrayFormattedTextValue
  >;
  image?: Array<
    {
      _key: string;
    } & CloudinaryAsset
  >;
};

export type Contribution = {
  _id: string;
  _type: 'contribution';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  donor: string;
  is_confirmed?: boolean;
  is_anonymous?: boolean;
  value?: number;
  contribution_date?: string;
  contribution_type?:
    | 'BANK'
    | 'CRYPTO'
    | 'WALL_NAME_SINGULAR'
    | 'WALL_NAME_COMPANY'
    | 'OFFICE_CHAIR'
    | 'SIMULATOR_CHAIR'
    | 'LOUNGE_CHAIR'
    | 'AUDITORIUM_CHAIR'
    | 'BUILDING_NAMING'
    | 'TRAINING_ROOM_NAMING';
};

export type Event = {
  _id: string;
  _type: 'event';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  image?: Array<
    {
      _key: string;
    } & CloudinaryAsset
  >;
};

export type Erasmus_project = {
  _id: string;
  _type: 'erasmus_project';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: Array<
    {
      _key: string;
    } & InternationalizedArrayFormattedTextValue
  >;
  image?: Array<
    {
      _key: string;
    } & CloudinaryAsset
  >;
};

export type Art = {
  _id: string;
  _type: 'art';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug?: Slug;
  description?: Array<
    {
      _key: string;
    } & InternationalizedArrayFormattedTextValue
  >;
  image?: CloudinaryAsset;
  art_properties?: Array<
    {
      _key: string;
    } & Art_property
  >;
  is_sold?: boolean;
};

export type Curator = {
  _id: string;
  _type: 'curator';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: Array<
    {
      _key: string;
    } & InternationalizedArrayFormattedTextValue
  >;
  image?: CloudinaryAsset;
};

export type Slug = {
  _type: 'slug';
  current: string;
  source?: string;
};

export type InternationalizedArrayFormattedTextValue = {
  _type: 'internationalizedArrayFormattedTextValue';
  value?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
};

export type InternationalizedArrayStringValue = {
  _type: 'internationalizedArrayStringValue';
  value?: string;
};

export type InternationalizedArrayFormattedText = Array<
  {
    _key: string;
  } & InternationalizedArrayFormattedTextValue
>;

export type InternationalizedArrayString = Array<
  {
    _key: string;
  } & InternationalizedArrayStringValue
>;

export type CloudinaryAssetContextCustom = {
  _type: 'cloudinary.assetContextCustom';
  alt?: string;
  caption?: string;
};

export type CloudinaryAssetDerived = {
  _type: 'cloudinary.assetDerived';
  raw_transformation?: string;
  url?: string;
  secure_url?: string;
};

export type CloudinaryAsset = {
  _type: 'cloudinary.asset';
  public_id?: string;
  resource_type?: string;
  type?: string;
  format?: string;
  version?: number;
  url?: string;
  secure_url?: string;
  width?: number;
  height?: number;
  bytes?: number;
  duration?: number;
  tags?: Array<string>;
  created_at?: string;
  derived?: Array<
    {
      _key: string;
    } & CloudinaryAssetDerived
  >;
  access_mode?: string;
  context?: CloudinaryAssetContext;
};

export type CloudinaryAssetContext = {
  _type: 'cloudinary.assetContext';
  custom?: CloudinaryAssetContextCustom;
};

export type AllSanitySchemaTypes =
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | SanityAssetSourceData
  | Art_property
  | Report
  | News
  | Contribution
  | Event
  | Erasmus_project
  | Art
  | Curator
  | Slug
  | InternationalizedArrayFormattedTextValue
  | InternationalizedArrayStringValue
  | InternationalizedArrayFormattedText
  | InternationalizedArrayString
  | CloudinaryAssetContextCustom
  | CloudinaryAssetDerived
  | CloudinaryAsset
  | CloudinaryAssetContext;
export declare const internalGroqTypeReferenceTo: unique symbol;
